Repository kc-learningmate/learningmate_be, pull requests merged in 2025-08, with the labels that each got.

#30 Feat/review 기사 리뷰 CRUD 구현
  build.gradle
  src/main/java/org/kc5/learningmate/api/v1/controller/ReviewController.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/review/ReviewCreateRequest.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/review/ReviewGetRequest.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/review/ReviewUpdateRequest.java
  src/main/java/org/kc5/learningmate/api/v1/dto/response/ReviewResponse.java
  src/main/java/org/kc5/learningmate/common/ResultResponse.java
  src/main/java/org/kc5/learningmate/common/exception/ErrorCode.java
  src/main/java/org/kc5/learningmate/domain/review/entity/Review.java
  src/main/java/org/kc5/learningmate/domain/review/repository/ReviewRepository.java
  src/main/java/org/kc5/learningmate/domain/review/service/ReviewService.java
Labels: feat✨

#34 Feat: 특정 키워드 상세 조회 #12
  src/main/java/org/kc5/learningmate/api/v1/controller/KeywordController.java
  src/main/java/org/kc5/learningmate/api/v1/dto/response/KeywordDto.java
  src/main/java/org/kc5/learningmate/api/v1/dto/response/KeywordResponse.java
  src/main/java/org/kc5/learningmate/api/v1/dto/response/TodaysKeywordDto.java
  src/main/java/org/kc5/learningmate/api/v1/dto/response/TodaysKeywordResponse.java
  src/main/java/org/kc5/learningmate/common/exception/ErrorCode.java
  src/main/java/org/kc5/learningmate/domain/keyword/service/KeywordService.java
Labels: feat✨

#37 Feat/quiz/get 기사에 대한 퀴즈 리스트로 받아오기
  src/main/java/org/kc5/learningmate/api/v1/controller/ArticleController.java
  src/main/java/org/kc5/learningmate/api/v1/dto/response/QuizResponse.java
  src/main/java/org/kc5/learningmate/common/exception/ErrorCode.java
  src/main/java/org/kc5/learningmate/domain/article/service/ArticleService.java
  src/main/java/org/kc5/learningmate/domain/quiz/repository/QuizRepository.java
Labels: fix🔨

#40 Feat/quiz like 리뷰 좋아요 및 취소
  src/main/java/org/kc5/learningmate/api/v1/controller/ReviewController.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/review/ReviewLikeRequest.java
  src/main/java/org/kc5/learningmate/domain/review/entity/LikeReview.java
  src/main/java/org/kc5/learningmate/domain/review/repository/LikeReviewRepository.java
  src/main/java/org/kc5/learningmate/domain/review/service/ReviewService.java
Labels: feat✨

#41 Feat: 특정 키워드 관련 기사 목록 조회 #10
  src/main/java/org/kc5/learningmate/api/v1/controller/KeywordController.java
  src/main/java/org/kc5/learningmate/api/v1/dto/response/ArticlePreviewResponse.java
  src/main/java/org/kc5/learningmate/common/exception/ErrorCode.java
  src/main/java/org/kc5/learningmate/domain/article/entity/Article.java
  src/main/java/org/kc5/learningmate/domain/article/repository/ArticleRepository.java
  src/main/java/org/kc5/learningmate/domain/article/service/ArticleService.java
Labels: feat✨

#42 feat: 기사 퀴즈 풀기 기능 구현
  src/main/java/org/kc5/learningmate/api/v1/controller/ArticleController.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/MemberQuizRequest.java
  src/main/java/org/kc5/learningmate/api/v1/dto/response/QuizResponse.java
  src/main/java/org/kc5/learningmate/common/exception/ErrorCode.java
  src/main/java/org/kc5/learningmate/domain/article/service/ArticleService.java
  src/main/java/org/kc5/learningmate/domain/quiz/entity/MemberQuiz.java
  src/main/java/org/kc5/learningmate/domain/quiz/repository/MemberQuizRepository.java
Labels: feat✨

#49 refactor: 리뷰 단일 조회반환 값 수정
  src/main/java/org/kc5/learningmate/api/v1/dto/response/MyReviewResponse.java
Labels: refactor🌈

#56 refactor: memberId 가져오는 방식 수정 #32
  src/main/java/org/kc5/learningmate/api/v1/controller/ArticleController.java
  src/main/java/org/kc5/learningmate/api/v1/controller/ReviewController.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/MemberQuizRequest.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/review/ReviewCreateRequest.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/review/ReviewGetRequest.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/review/ReviewLikeRequest.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/review/ReviewUpdateRequest.java
  src/main/java/org/kc5/learningmate/domain/article/service/ArticleService.java
  src/main/java/org/kc5/learningmate/domain/review/service/ReviewService.java
Labels: refactor🌈

#65 Feat: 비밀번호 찾기 및 비밀번호 재설정
  build.gradle
  src/main/java/org/kc5/learningmate/api/v1/controller/ArticleController.java
  src/main/java/org/kc5/learningmate/api/v1/controller/AuthController.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/auth/AuthCodeGetRequest.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/auth/AuthCodeRequest.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/auth/AuthCodeValidateRequest.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/auth/LoginRequest.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/auth/PasswdResetRequest.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/auth/SendResetPasswdRequest.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/member/MemberQuizRequest.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/member/MemberRequest.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/member/MemberUpdateRequest.java
  src/main/java/org/kc5/learningmate/common/constants/EmailConstants.java
  src/main/java/org/kc5/learningmate/common/exception/ErrorCode.java
  src/main/java/org/kc5/learningmate/config/MemberSecurityConfig.java
  src/main/java/org/kc5/learningmate/domain/article/service/ArticleService.java
  src/main/java/org/kc5/learningmate/domain/auth/properties/AuthProperties.java
  src/main/java/org/kc5/learningmate/domain/auth/service/AuthService.java
  src/main/java/org/kc5/learningmate/domain/auth/service/EmailService.java
  src/main/java/org/kc5/learningmate/domain/member/entity/Member.java
  src/main/java/org/kc5/learningmate/domain/member/service/MemberService.java
  src/main/resources/templates/auth-code-email.html
  src/main/resources/templates/passwd-reset-email.html
Labels: feat✨

#67 Fix/reset passwd
  src/main/java/org/kc5/learningmate/domain/auth/service/AuthService.java
  src/main/resources/templates/passwd-reset-email.html
Labels: fix🔨

#69 feat: member / 사용자 프로필 수정 #68
  src/main/java/org/kc5/learningmate/api/v1/controller/MemberController.java
  src/main/java/org/kc5/learningmate/api/v1/dto/request/member/MemberUpdateRequest.java
  src/main/java/org/kc5/learningmate/common/exception/ErrorCode.java
  src/main/java/org/kc5/learningmate/common/exception/GlobalExceptionHandler.java
  src/main/java/org/kc5/learningmate/domain/member/entity/Member.java
  src/main/java/org/kc5/learningmate/domain/member/repository/MemberRepository.java
  src/main/java/org/kc5/learningmate/domain/member/service/ImageService.java
  src/main/java/org/kc5/learningmate/domain/member/service/MemberService.java
Labels: feat✨

#73 Refactor/profile
  src/main/java/org/kc5/learningmate/api/v1/controller/MemberController.java
  src/main/java/org/kc5/learningmate/domain/member/service/MemberService.java
Labels: refactor🌈

#76 Refactor: member / 프로필 업데이트 반환값 수정
  src/main/java/org/kc5/learningmate/api/v1/controller/MemberController.java
  src/main/java/org/kc5/learningmate/common/exception/ErrorCode.java
  src/main/java/org/kc5/learningmate/domain/member/service/ImageService.java
  src/main/java/org/kc5/learningmate/domain/member/service/MemberService.java
Labels: refactor🌈
